/**
 * Curated catalog for the Discover tab. These are pullable Ollama library names —
 * the Models page also accepts any arbitrary `name:tag`, so this list is a
 * starting point, not a limit.
 */
export const CATEGORIES = [
  { id: 'all', label: 'All models' },
  { id: 'general', label: 'General purpose' },
  { id: 'vision', label: 'Vision' },
  { id: 'reasoning', label: 'Reasoning' },
  { id: 'code', label: 'Code' },
  { id: 'small', label: 'Small & fast' },
  { id: 'embedding', label: 'Embeddings' },
]

export const CATALOG = [
  {
    id: 'llama3.2',
    name: 'Llama 3.2',
    publisher: 'Meta',
    categories: ['general', 'small'],
    description:
      'Meta\'s compact general-purpose model. Excellent quality for its size and quick on a laptop.',
    variants: [
      { tag: 'llama3.2:1b', label: '1B', size: '1.3 GB', ram: '4 GB' },
      { tag: 'llama3.2:3b', label: '3B', size: '2.0 GB', ram: '8 GB', recommended: true },
    ],
  },
  {
    id: 'llama3.1',
    name: 'Llama 3.1',
    publisher: 'Meta',
    categories: ['general'],
    description: 'Strong all-round assistant with a 128K context window and solid tool use.',
    variants: [
      { tag: 'llama3.1:8b', label: '8B', size: '4.9 GB', ram: '16 GB', recommended: true },
      { tag: 'llama3.1:70b', label: '70B', size: '40 GB', ram: '64 GB' },
    ],
  },
  {
    id: 'qwen2.5',
    name: 'Qwen 2.5',
    publisher: 'Alibaba',
    categories: ['general'],
    description: 'Multilingual model with strong reasoning and instruction following across sizes.',
    variants: [
      { tag: 'qwen2.5:0.5b', label: '0.5B', size: '400 MB', ram: '4 GB' },
      { tag: 'qwen2.5:3b', label: '3B', size: '1.9 GB', ram: '8 GB' },
      { tag: 'qwen2.5:7b', label: '7B', size: '4.7 GB', ram: '16 GB', recommended: true },
      { tag: 'qwen2.5:14b', label: '14B', size: '9.0 GB', ram: '32 GB' },
      { tag: 'qwen2.5:32b', label: '32B', size: '20 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'qwen3',
    name: 'Qwen 3',
    publisher: 'Alibaba',
    categories: ['general', 'reasoning'],
    description: 'Latest Qwen generation with a switchable thinking mode for harder problems.',
    variants: [
      { tag: 'qwen3:1.7b', label: '1.7B', size: '1.4 GB', ram: '8 GB' },
      { tag: 'qwen3:4b', label: '4B', size: '2.6 GB', ram: '8 GB' },
      { tag: 'qwen3:8b', label: '8B', size: '5.2 GB', ram: '16 GB', recommended: true },
      { tag: 'qwen3:14b', label: '14B', size: '9.3 GB', ram: '32 GB' },
      { tag: 'qwen3:32b', label: '32B', size: '20 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'gemma3',
    name: 'Gemma 3',
    publisher: 'Google',
    categories: ['general', 'vision'],
    description: 'Google\'s open model family. The 4B and larger variants can read images.',
    vision: true,
    variants: [
      { tag: 'gemma3:1b', label: '1B', size: '815 MB', ram: '4 GB' },
      { tag: 'gemma3:4b', label: '4B', size: '3.3 GB', ram: '8 GB', recommended: true },
      { tag: 'gemma3:12b', label: '12B', size: '8.1 GB', ram: '24 GB' },
      { tag: 'gemma3:27b', label: '27B', size: '17 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'phi4',
    name: 'Phi 4',
    publisher: 'Microsoft',
    categories: ['general', 'reasoning'],
    description: 'Punches well above its weight on maths and reasoning benchmarks.',
    variants: [{ tag: 'phi4:14b', label: '14B', size: '9.1 GB', ram: '24 GB', recommended: true }],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    publisher: 'Mistral AI',
    categories: ['general'],
    description: 'Fast, efficient 7B model that remains a great everyday default.',
    variants: [{ tag: 'mistral:7b', label: '7B', size: '4.1 GB', ram: '16 GB', recommended: true }],
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral Nemo',
    publisher: 'Mistral AI',
    categories: ['general'],
    description: 'A 12B model built with NVIDIA, with a large 128K context window.',
    variants: [{ tag: 'mistral-nemo:12b', label: '12B', size: '7.1 GB', ram: '24 GB' }],
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    publisher: 'DeepSeek',
    categories: ['reasoning'],
    description: 'Open reasoning model that shows its chain of thought before answering.',
    reasoning: true,
    variants: [
      { tag: 'deepseek-r1:1.5b', label: '1.5B', size: '1.1 GB', ram: '8 GB' },
      { tag: 'deepseek-r1:7b', label: '7B', size: '4.7 GB', ram: '16 GB', recommended: true },
      { tag: 'deepseek-r1:8b', label: '8B', size: '4.9 GB', ram: '16 GB' },
      { tag: 'deepseek-r1:14b', label: '14B', size: '9.0 GB', ram: '32 GB' },
      { tag: 'deepseek-r1:32b', label: '32B', size: '20 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'qwq',
    name: 'QwQ',
    publisher: 'Alibaba',
    categories: ['reasoning'],
    description: 'Reasoning-focused model that works through problems step by step.',
    reasoning: true,
    variants: [{ tag: 'qwq:32b', label: '32B', size: '20 GB', ram: '48 GB' }],
  },
  {
    id: 'llama3.2-vision',
    name: 'Llama 3.2 Vision',
    publisher: 'Meta',
    categories: ['vision'],
    description: 'Reads images: describe photos, read charts, extract text from screenshots.',
    vision: true,
    variants: [
      { tag: 'llama3.2-vision:11b', label: '11B', size: '7.9 GB', ram: '24 GB', recommended: true },
      { tag: 'llama3.2-vision:90b', label: '90B', size: '55 GB', ram: '96 GB' },
    ],
  },
  {
    id: 'llava',
    name: 'LLaVA',
    publisher: 'Open source',
    categories: ['vision', 'small'],
    description: 'The classic lightweight vision model — a good first choice for image chat.',
    vision: true,
    variants: [
      { tag: 'llava:7b', label: '7B', size: '4.7 GB', ram: '16 GB', recommended: true },
      { tag: 'llava:13b', label: '13B', size: '8.0 GB', ram: '24 GB' },
      { tag: 'llava:34b', label: '34B', size: '20 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'moondream',
    name: 'Moondream',
    publisher: 'Open source',
    categories: ['vision', 'small'],
    description: 'Tiny vision model that runs comfortably on almost any machine.',
    vision: true,
    variants: [{ tag: 'moondream:1.8b', label: '1.8B', size: '1.7 GB', ram: '4 GB' }],
  },
  {
    id: 'minicpm-v',
    name: 'MiniCPM-V',
    publisher: 'OpenBMB',
    categories: ['vision'],
    description: 'Strong OCR and document understanding for its size.',
    vision: true,
    variants: [{ tag: 'minicpm-v:8b', label: '8B', size: '5.5 GB', ram: '16 GB' }],
  },
  {
    id: 'qwen2.5-coder',
    name: 'Qwen 2.5 Coder',
    publisher: 'Alibaba',
    categories: ['code'],
    description: 'Purpose-built for programming: generation, refactoring, and code review.',
    variants: [
      { tag: 'qwen2.5-coder:1.5b', label: '1.5B', size: '1.0 GB', ram: '8 GB' },
      { tag: 'qwen2.5-coder:7b', label: '7B', size: '4.7 GB', ram: '16 GB', recommended: true },
      { tag: 'qwen2.5-coder:14b', label: '14B', size: '9.0 GB', ram: '32 GB' },
      { tag: 'qwen2.5-coder:32b', label: '32B', size: '20 GB', ram: '48 GB' },
    ],
  },
  {
    id: 'codellama',
    name: 'Code Llama',
    publisher: 'Meta',
    categories: ['code'],
    description: 'Meta\'s code model, tuned for completion and infilling.',
    variants: [
      { tag: 'codellama:7b', label: '7B', size: '3.8 GB', ram: '16 GB' },
      { tag: 'codellama:13b', label: '13B', size: '7.4 GB', ram: '24 GB' },
    ],
  },
  {
    id: 'codegemma',
    name: 'CodeGemma',
    publisher: 'Google',
    categories: ['code', 'small'],
    description: 'Lightweight coding assistant that stays responsive on modest hardware.',
    variants: [{ tag: 'codegemma:7b', label: '7B', size: '5.0 GB', ram: '16 GB' }],
  },
  {
    id: 'smollm2',
    name: 'SmolLM 2',
    publisher: 'Hugging Face',
    categories: ['small'],
    description: 'Extremely small models for quick tasks and low-memory machines.',
    variants: [
      { tag: 'smollm2:135m', label: '135M', size: '271 MB', ram: '2 GB' },
      { tag: 'smollm2:1.7b', label: '1.7B', size: '1.8 GB', ram: '8 GB' },
    ],
  },
  {
    id: 'tinyllama',
    name: 'TinyLlama',
    publisher: 'Open source',
    categories: ['small'],
    description: 'A 1.1B model for testing pipelines and very constrained hardware.',
    variants: [{ tag: 'tinyllama:1.1b', label: '1.1B', size: '638 MB', ram: '2 GB' }],
  },
  {
    id: 'nomic-embed-text',
    name: 'Nomic Embed Text',
    publisher: 'Nomic AI',
    categories: ['embedding'],
    description: 'High-quality text embeddings for search and retrieval workflows.',
    embedding: true,
    variants: [{ tag: 'nomic-embed-text:latest', label: 'v1.5', size: '274 MB', ram: '2 GB' }],
  },
  {
    id: 'mxbai-embed-large',
    name: 'mxbai Embed Large',
    publisher: 'Mixedbread AI',
    categories: ['embedding'],
    description: 'Large embedding model with strong retrieval benchmark scores.',
    embedding: true,
    variants: [{ tag: 'mxbai-embed-large:latest', label: '335M', size: '670 MB', ram: '4 GB' }],
  },
]

/** Suggestion chips shown on the empty-chat welcome screen. */
export const STARTERS = [
  { icon: 'sparkle', label: 'Explain a concept', prompt: 'Explain how transformers work, in plain language.' },
  { icon: 'code', label: 'Write some code', prompt: 'Write a Python script that renames every file in a folder to include its creation date.' },
  { icon: 'image', label: 'Analyse an image', prompt: 'I\'m going to upload an image — tell me everything you can about it.' },
  { icon: 'edit', label: 'Help me write', prompt: 'Help me write a short, friendly email asking a colleague for an update on a project.' },
  { icon: 'bulb', label: 'Brainstorm ideas', prompt: 'Give me 10 unusual weekend project ideas I could build in a day.' },
  { icon: 'chart', label: 'Make a plan', prompt: 'Help me plan a 4-week schedule to learn a new programming language.' },
]
